import { Product } from './types/Product';

export const sampleProducts: Product[] = [
    {
        name: 'Nike slim shirt',
        slug: 'nike-slim-shirt0',
        category: 'Shirts',
        image: '../images/p1.png',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'This is nike shirt',
    },
    {
        name: 'Nike slim shirt',
        slug: 'nike-slim-shirt',
        category: 'Shirts',
        image: '../images/p1.png',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'This is nike shirt',
    },
    {
        name: 'Nike slim shirt',
        slug: 'nike-slim-shirt1',
        category: 'Shirts',
        image: '../images/p1.png',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'This is nike shirt',
    },
    {
        name: 'Nike slim shirt',
        slug: 'nike-slim-shirt2',
        category: 'Shirts',
        image: '../images/p1.png',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'This is nike shirt',
    },
    {
        name: 'Nike slim shirt',
        slug: 'nike-slim-shirt3',
        category: 'Shirts',
        image: '../images/p1.png',
        price: 120,
        countInStock: 10,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'This is nike shirt',
    },
];
